module.exports = {
  EARTH_RADIUS_KM: 6378.137,
  MAX_PATIENT_DISTANCE: 800,
  WEIGHT_ACCEPTED_OFFERS: 0.3,
  WEIGHT_AGE: 0.1,
  WEIGHT_CANCELLED_OFFERS: 0.3,
  WEIGHT_DISTANCE: 0.1,
  WEIGHT_REPLY_TIME: 0.2,
};